export type Classe = {
  id: number
  status: number
  periodo_letivo?: string
  codigo?: string
  disciplina: string
  situacao: string
  nota?: string
  faltas?: number
  creditos: number
  cargaHoraria: number
  cargaHorariaIntegralizada?: number
}

export type Classes = {
  id: number
  nome: string
  categoria: string
  classes: Classe[]
}

export const classes: Classes[] = [
  {
    id: 1,
    nome: '1º Período',
    categoria: 'disciplina-obrigatorias',
    classes: [
      {
        id: 1,
        status: 1,
        codigo: '204301',
        disciplina: 'Algoritmos e Linguagens de Programação',
        situacao: '*Equiv.',
        creditos: 4,
        cargaHoraria: 80,
        cargaHorariaIntegralizada: 80,
      },
      {
        id: 2,
        status: 4,
        periodo_letivo: '2021/1',
        codigo: '204201',
        disciplina: 'Codificação de Software',
        situacao: 'Aprovado',
        nota: '9,00',
        faltas: 0,
        creditos: 8,
        cargaHoraria: 160,
      },
      {
        id: 3,
        status: 1,
        codigo: '204303',
        disciplina: 'Arquitetura e Organização de Computadores',
        situacao: '*Equiv.',
        creditos: 4,
        cargaHoraria: 80,
        cargaHorariaIntegralizada: 80,
      },
      {
        id: 4,
        status: 4,
        periodo_letivo: '2022/1',
        codigo: '204209',
        disciplina: 'Tecnologia da Informação',
        situacao: 'Aprovado',
        nota: 'SATISF',
        faltas: 13,
        creditos: 6,
        cargaHoraria: 120,
      },
      {
        id: 5,
        status: 1,
        codigo: '204305',
        disciplina: 'Lógica',
        situacao: '*Equiv.',
        creditos: 4,
        cargaHoraria: 80,
        cargaHorariaIntegralizada: 80,
      },
      {
        id: 6,
        status: 4,
        periodo_letivo: '2021/2',
        codigo: '204205',
        disciplina: 'Engenharia do Conhecimento',
        situacao: 'Aprovado',
        nota: '9,00',
        faltas: 0,
        creditos: 6,
        cargaHoraria: 120,
      },
      {
        id: 7,
        status: 1,
        codigo: '204302',
        disciplina: 'Matemática Discreta',
        situacao: '*Equiv.',
        creditos: 4,
        cargaHoraria: 80,
        cargaHorariaIntegralizada: 80,
      },
      {
        id: 8,
        status: 4,
        periodo_letivo: '2021/1',
        codigo: '204201',
        disciplina: 'Codificação de Software',
        situacao: 'Aprovado',
        nota: '9,00',
        faltas: 0,
        creditos: 8,
        cargaHoraria: 160,
      },
      {
        id: 9,
        status: 1,
        codigo: '204304',
        disciplina:
          'Práticas Profissionais em Ética e Legislação em Engenharia de Software',
        situacao: '*Equiv.',
        creditos: 3,
        cargaHoraria: 60,
        cargaHorariaIntegralizada: 60,
      },
      {
        id: 10,
        status: 4,
        periodo_letivo: '2022/2',
        codigo: '204211',
        disciplina: 'Tecnologias Aplicadas à Gestão de Negócios',
        situacao: 'Aprovado',
        nota: '0,00/SATISF',
        faltas: 30,
        creditos: 6,
        cargaHoraria: 120,
      },
    ],
  },
  {
    id: 2,
    nome: '2º Período',
    categoria: 'disciplina-obrigatorias',
    classes: [
      {
        id: 11,
        status: 1,
        codigo: '204306',
        disciplina: 'Engenharia de Software I',
        situacao: '*Equiv.',
        creditos: 4,
        cargaHoraria: 80,
        cargaHorariaIntegralizada: 80,
      },
      {
        id: 12,
        status: 4,
        periodo_letivo: '2021/2',
        codigo: '204206',
        disciplina: 'Engenharia de Requisitos',
        situacao: 'Aprovado',
        nota: '8,67',
        faltas: 0,
        creditos: 6,
        cargaHoraria: 120,
      },
      {
        id: 13,
        status: 1,
        periodo_letivo: '2024/1',
        codigo: '204310',
        disciplina: 'Linguagens, Autômatos e Computação',
        situacao: 'Aprovado',
        nota: '9,50',
        faltas: 12,
        creditos: 4,
        cargaHoraria: 80,
        cargaHorariaIntegralizada: 80,
      },
      {
        id: 14,
        status: 1,
        codigo: '204308',
        disciplina: 'Relações Princípios e Valores',
        situacao: '*Equiv.',
        creditos: 4,
        cargaHoraria: 80,
        cargaHorariaIntegralizada: 80,
      },
      {
        id: 15,
        status: 4,
        periodo_letivo: '2021/1',
        codigo: '204204',
        disciplina: 'Relação: Princípios e Valores',
        situacao: 'Aprovado',
        nota: '10',
        faltas: 8,
        creditos: 4,
        cargaHoraria: 80,
      },
      {
        id: 16,
        status: 1,
        codigo: '204307',
        disciplina: 'Sistemas de Banco de Dados I',
        situacao: '*Equiv.',
        creditos: 4,
        cargaHoraria: 80,
        cargaHorariaIntegralizada: 80,
      },
      {
        id: 17,
        status: 4,
        periodo_letivo: '2021/1',
        codigo: '204202',
        disciplina: 'Sistema de Gerenciamento de Banco de Dados',
        situacao: 'Aprovado',
        nota: '9,50',
        faltas: 8,
        creditos: 6,
        cargaHoraria: 120,
      },
      {
        id: 18,
        status: 3,
        periodo_letivo: '2024/2',
        codigo: '204309',
        disciplina: 'Práticas Profissionais em Construção de Software',
        situacao: 'Matriculado',
        nota: '8,80',
        faltas: 4,
        creditos: 3,
        cargaHoraria: 60,
      },
    ],
  },
  {
    id: 3,
    nome: '3º Período',
    categoria: 'Período',
    classes: [
      {
        id: 19,
        status: 1,
        codigo: '204313',
        disciplina: 'Engenharia de Software II',
        situacao: '*Equiv.',
        creditos: 4,
        cargaHoraria: 80,
        cargaHorariaIntegralizada: 80,
      },
      {
        id: 20,
        status: 4,
        periodo_letivo: '2022/1',
        codigo: '204208',
        disciplina: 'Engenharia de Software',
        situacao: 'Aprovado',
        nota: 'SATISF',
        faltas: 6,
        creditos: 6,
        cargaHoraria: 120,
      },
      {
        id: 21,
        status: 1,
        codigo: '204314',
        disciplina: 'Estatística Aplicada a Engenharia de Software',
        situacao: '*Equiv.',
        creditos: 4,
        cargaHoraria: 80,
        cargaHorariaIntegralizada: 80,
      },
      {
        id: 22,
        status: 4,
        periodo_letivo: '2024/2',
        codigo: '301411',
        disciplina: 'Estatística',
        situacao: 'Aprovado',
        nota: '7',
        faltas: 0,
        creditos: 4,
        cargaHoraria: 80,
      },
      {
        id: 23,
        status: 1,
        periodo_letivo: '2023/1',
        codigo: '204312',
        disciplina: 'Estrutura de Dados',
        situacao: 'Aprovado',
        nota: '7,85',
        creditos: 4,
        cargaHoraria: 80,
        cargaHorariaIntegralizada: 80,
      },
      {
        id: 24,
        status: 1,
        codigo: '204311',
        disciplina: 'Fundamentos de Processos de Negócios',
        situacao: '*Equiv.',
        creditos: 4,
        cargaHoraria: 80,
        cargaHorariaIntegralizada: 80,
      },
      {
        id: 25,
        status: 4,
        periodo_letivo: '2022/2',
        codigo: '204211',
        disciplina: 'Tecnologias Aplicadas à Gestão de Negócios',
        situacao: 'Aprovado',
        nota: '0/SATISF',
        faltas: 30,
        creditos: 6,
        cargaHoraria: 120,
      },
      {
        id: 26,
        status: 1,
        codigo: '204315',
        disciplina:
          'Unidade Extensionista Mapeamento de Processos Organizacionais',
        situacao: '*Equiv.',
        creditos: 4,
        cargaHoraria: 80,
        cargaHorariaIntegralizada: 80,
      },
      {
        id: 27,
        status: 4,
        periodo_letivo: '2021/1',
        codigo: '204203',
        disciplina: 'Unidade Extensionista-Projeto Integrador I',
        situacao: 'Aprovado',
        nota: '8,50',
        faltas: 0,
        creditos: 2,
        cargaHoraria: 40,
      },
      {
        id: 28,
        status: 4,
        periodo_letivo: '2021/2',
        codigo: '204207',
        disciplina: 'Unidade Extensionista-Projeto Integrador II',
        situacao: 'Aprovado',
        nota: '9',
        faltas: 0,
        creditos: 2,
        cargaHoraria: 40,
      },
    ],
  },
  {
    id: 4,
    nome: '4º Período',
    categoria: 'Período',
    classes: [
      {
        id: 29,
        status: 1,
        periodo_letivo: '',
        codigo: '204320',
        disciplina: 'Empreendedorismo e Sustentabilidade',
        situacao: '*Equiv.',
        creditos: 4,
        cargaHoraria: 80,
        cargaHorariaIntegralizada: 80,
      },
      {
        id: 30,
        status: 4,
        periodo_letivo: '2022/1',
        codigo: '301410',
        disciplina: 'Empreendedorismo',
        situacao: 'Aprovado',
        nota: '7',
        faltas: 8,
        creditos: 4,
        cargaHoraria: 80,
      },
      {
        id: 31,
        status: 1,
        periodo_letivo: '2023/1',
        codigo: '204316',
        disciplina: 'Programação Orientada a Objetos',
        situacao: 'Aprovado',
        nota: '9,30',
        creditos: 4,
        cargaHoraria: 80,
        cargaHorariaIntegralizada: 80,
      },
      {
        id: 32,
        status: 1,
        periodo_letivo: '',
        codigo: '204317',
        disciplina: 'Redes de Computadores',
        situacao: '*Equiv.',
        creditos: 4,
        cargaHoraria: 80,
        cargaHorariaIntegralizada: 80,
      },
      {
        id: 33,
        status: 4,
        periodo_letivo: '2022/1',
        codigo: '204209',
        disciplina: 'Tecnologia da Informação',
        situacao: 'Aprovado',
        nota: 'SATISF',
        faltas: 13,
        creditos: 6,
        cargaHoraria: 120,
      },
      {
        id: 34,
        status: 1,
        periodo_letivo: '',
        codigo: '204319',
        disciplina: 'Sistemas de Banco de Dados II',
        situacao: '*Equiv.',
        creditos: 4,
        cargaHoraria: 80,
        cargaHorariaIntegralizada: 80,
      },
      {
        id: 35,
        status: 4,
        periodo_letivo: '2021/1',
        codigo: '204202',
        disciplina: 'Sistema de Gerenciamento de Banco de Dados',
        situacao: 'Aprovado',
        nota: '9,50',
        faltas: 8,
        creditos: 6,
        cargaHoraria: 120,
      },
      {
        id: 36,
        status: 1,
        periodo_letivo: '',
        codigo: '204318',
        disciplina: 'Soluções para Internet',
        situacao: '*Equiv.',
        creditos: 4,
        cargaHoraria: 80,
        cargaHorariaIntegralizada: 80,
      },
      {
        id: 37,
        status: 4,
        periodo_letivo: '2022/2',
        codigo: '204212',
        disciplina: 'Soluções para Internet',
        situacao: 'Aprovado',
        nota: '0/SATISF',
        faltas: 21,
        creditos: 6,
        cargaHoraria: 120,
      },
    ],
  },
  {
    id: 5,
    nome: '5º Período',
    categoria: 'Período',
    classes: [
      {
        id: 38,
        status: 1,
        periodo_letivo: '2023/1',
        codigo: '204322',
        disciplina: 'Interação Humano Computador',
        situacao: 'Aprovado',
        nota: '9,05',
        creditos: 4,
        cargaHoraria: 80,
        cargaHorariaIntegralizada: 80,
      },
      {
        id: 39,
        status: 1,
        periodo_letivo: '',
        codigo: '204321',
        disciplina: 'Profissão: Competências e Habilidades',
        situacao: '*Equiv.',
        creditos: 4,
        cargaHoraria: 80,
        cargaHorariaIntegralizada: 80,
      },
      {
        id: 40,
        status: 4,
        periodo_letivo: '2022/2',
        codigo: '204213',
        disciplina: 'Profissão: Competências e Habilidades',
        situacao: 'Aprovado',
        nota: 'SATISF',
        faltas: 8,
        creditos: 4,
        cargaHoraria: 80,
      },
      {
        id: 41,
        status: 1,
        periodo_letivo: '2023/1',
        codigo: '204325',
        disciplina: 'Soluções Dispositivos Móveis I',
        situacao: 'Aprovado',
        nota: '9,1',
        creditos: 4,
        cargaHoraria: 80,
        cargaHorariaIntegralizada: 80,
      },
      {
        id: 42,
        status: 1,
        periodo_letivo: '2023/1',
        codigo: '204323',
        disciplina: 'Teste e Qualidade de Software',
        situacao: 'Aprovado',
        nota: '8,1',
        creditos: 4,
        cargaHoraria: 80,
        cargaHorariaIntegralizada: 80,
      },
      {
        id: 43,
        status: 1,
        periodo_letivo: '',
        codigo: '204324',
        disciplina: 'Unidade Extensionista em Projeto de Software',
        situacao: '*Equiv.',
        creditos: 4,
        cargaHoraria: 80,
        cargaHorariaIntegralizada: 80,
      },
      {
        id: 44,
        status: 4,
        periodo_letivo: '2022/1',
        codigo: '204210',
        disciplina: 'Unidade Extensionista-Projeto Integrador III',
        situacao: 'Aprovado',
        nota: 'SATISF',
        faltas: 0,
        creditos: 4,
        cargaHoraria: 80,
      },
    ],
  },
  {
    id: 6,
    categoria: 'componentes-curriculares',
    nome: 'Componente Curricular: Ensino',
    classes: [
      {
        id: 45,
        cargaHoraria: 80,
        disciplina: 'Curso ignite reactjs',
        periodo_letivo: '2023/2',
        situacao: 'Concluída',
        creditos: 0,
        cargaHorariaIntegralizada: 80,
        status: 1,
      },
    ],
  },
]
